spring:
  application:
    name: tipo-cambio
  jackson:
    serialization:
      write-dates-as-timestamps: false
  # ===============================
  # = SECURITY CONFIG
  # ===============================
  security:
    user:
      name: admin
      password: mila
      roles: ADMIN

  # ===============================
  # = DATA SOURCE H2
  # ===============================
  h2:    console:      enabled: true
      path: /h2-console
      settings:        web-allow-others: false
      
        
server:
  port: 9999
      